# Generated by Django 5.0.6 on 2024-05-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=255)),
                ("meaning", models.TextField()),
                ("example_sentence", models.TextField(blank=True, null=True)),
                ("extra_info", models.TextField(blank=True, null=True)),
                ("synonyms", models.ManyToManyField(blank=True, to="vocabulary.word")),
            ],
        ),
    ]
