# Generated by Django 5.0.6 on 2024-05-30 10:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlackToken",
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
